---
name: "Integration Tests"

concurrency:
  group: integration-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:

jobs:
  safe-to-test:
    if: >-
      github.event.label.name == 'safe to test' ||
      github.event.action != 'labeled'
    uses: ansible-network/github_actions/.github/workflows/safe-to-test.yml@main

  integration:
    name: Integration Tests
    runs-on: [rhel]
    needs:
      - safe-to-test
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ansible_collections/splunk/enterprise
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install ansible-core
        run: |
          source ~/venv-runner/bin/activate
          pip install ansible-core

      - name: Install collection dependencies
        run: |
          source ~/venv-runner/bin/activate
          ansible-galaxy collection install ansible.netcommon ansible.utils -p ./ansible_collections

      - name: Run integration tests
        working-directory: ansible_collections/splunk/enterprise
        run: |
          source ~/venv-runner/bin/activate
          ansible-test integration -v --color yes
